---

- name: Set CCI permisisons
  shell: "{{ item }}"
  args:
    warn:false
  with_items:
    - "touch /HORCM/etc/USE_OLD_IOCT"
    - "chown lpar2rrd /HORCM"
    - "chown -R lpar2rrd /HORCM/* /HORCM/.uds"
    - "chmod 755 /HORCM /HORCM/usr/bin /HORCM/usr/bin/* /HORCM/log* /HORCM/etc/horcmgr /HORCM/etc/*conf /HORCM/.uds/"
  

- name: Ensure directory /opt/hds/firmware_version are exists
  file:
    path: /opt/hds/{{ firmware_version }}
    state: directory
    mode: 0755

- name: Extract files
  unarchive:
    src: '{{ firmware_version }}/export.tar'
    dest: /opt/hds/{{ firmware_version }}

- name: Set folder owner
  shell: chown -R lpar2rrd /opt/hds
  args:
    warn:false
#  file:
#    path: /home/lpar2rrd/stor2rrd/
#    owner: root

