---

- name: Ensure directory /opt/hds/firmware_version are exists
  file:
    path: /opt/hds/{{ firmware_version }}
    state: directory
    mode: 0755

- name: Copy install files
  copy:
    src: export.tar
    dest: /opt/hds/{{ firmware_version }}

- name: Extract files
  unarchive:
    src: /opt/hds/{{ firmware_version }}/export.tar
    dest: /opt/hds/{{ firmware_version }}
