---

- name: Ensure directory /opt/hds/firmware_version are exists
  file:
    path: /opt/hds/{{ firmware_version }}
    state: directory
    mode: 0755

- name: Extract files
  unarchive:
    src: export.tar
    dest: /opt/hds/{{ firmware_version }}

- name: Set directory owner
  file:
    path: /opt/hds
    owner: stor2rrd
