---

- name: Set folder owner
  shell: chown -R root /home/lpar2rrd/stor2rrd/
#  file:
#    path: /home/lpar2rrd/stor2rrd/
#    owner: root

- name: Configure Export Tool installation directory
  replace:
    path: /home/stor2rrd/stor2rrd/etc/stor2rrd.cfg
    regexp: '^  VSP_CLIDIR=/usr'
    replace: '  VSP_CLIDIR=/opt/hds'
    backup: yes

- name: Configure storage-list
  lineinfile:
    dest: /home/stor2rrd/stor2rrd/etc/storage-list.cfg
    state: present
    insertafter: "^# Hitachi VSP-G"
    line: "{{ item }}"
  with_items:
    - {{ VSP1_ALIAS }}:VSPG:{{ VSP1_IP }}:maintenance:KzImRVQwIyhQLDM5JDo3MGAK:/etc/{{ HORCM_VSP1 }}
    - {{ VSP2_ALIAS }}:VSPG:{{ VSP2_IP }}:maintenance:KzImRVQwIyhQLDM5JDo3MGAK:/etc/{{ HORCM_VSP2 }}

- name: Check connection
  shell: ./config_check.sh
  args:
    chdir: /home/stor2rrd/stor2rrd/bin
  register: result

- name: Debug
  debug: 
    var: result.stdout

- name: Set crontab -e
  lineinfile:
    dest: /var/spool/cron/root
    state: present
    insertafter: "^#"
    line: "{{ item }}"
  with_items:
     - 0,5,10,15,20,25,30,35,40,45,50,55 * * * * /home/stor2rrd/stor2rrd/load_vspgperf.sh > /home/stor2rrd/stor2rrd/load_vspgperf.out
     - 0 * * * * /home/stor2rrd/stor2rrd/load.sh > /home/stor2rrd/stor2rrd/load.out 2>&1    
