---
# tasks file for roles/xorux_config


- include: 00-hostname.yml
  tags: hostname

- include_role:
    name: miquelMariano.hitachiCCI  
  tags: cci
  vars:
    install: true
    SN_VSP1: 470853
    SN_VSP2: 471006


