---
# tasks file for roles/xorux_config


- include: 00-hostname.yml
  tags: hostname

#- include_role:
#    name: miquelmariano.hitachicci  
#  tags: cci
#  vars:
#    install: true
#    SN_VSP1: 470853
#    SN_VSP2: 471006

- name: Stop HORCM
  shell: horcmshutdown.sh 300 301 63
  ignore_errors: yes   

- name: Start HORCM
  shell: horcmstart.sh 300 301 63
  ignore_errors: yes   

- include: 01-export-tool.yml
  tags: export-tool

- include: 02-STOR2RRD-storage-configuration.yml
  tags: configuration


